version: 2.1

orbs:
  node: circleci/node@5.1
  slack: circleci/slack@4.12

jobs:
  lint:
    working_directory: ~/what3idols
    executor:
      name: node/default
      tag: '18.5-browsers'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: lint
          command: yarn lint
  deploy:
    working_directory: ~/what3idols
    executor:
      name: node/default
      tag: '18.5-browsers'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: deploy
          command: yarn deploy
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  main:
    jobs:
      - lint
      - deploy:
          context:
            - slack
          requires:
            - lint
          filters:
            branches:
              only:
                - main
