version: 2.1

orbs:
  node: circleci/node@5.0
  slack: circleci/slack@4.4.2

jobs:
  lint:
    working_directory: ~/what3idols
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: false
      - run:
          name: lint
          command: yarn lint
  deploy:
    working_directory: ~/what3idols
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: false
      - run:
          name: deploy
          command: yarn deploy
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  version: 2
  main:
    jobs:
      - lint
      - deploy:
          context:
            - slack
          requires:
            - lint
          filters:
            branches:
              only:
                - main
