version: 2.1

orbs:
  node: circleci/node@5.0
  slack: circleci/slack@4.4.2

jobs:
  lint:
    working_directory: ~/what3idols
    executor:
      name: node/default
      tag: '16.14.0-browsers'
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: false
      - run:
          name: lint
          command: yarn lint
  typecheck:
    working_directory: ~/what3idols
    executor:
      name: node/default
      tag: '16.14.0-browsers'
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: false
      - run:
          name: typecheck
          command: yarn tsc
  deploy:
    working_directory: ~/what3idols
    executor:
      name: node/default
      tag: '16.14.0-browsers'
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: false
      - run:
          name: deploy
          command: yarn deploy
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  version: 2
  main:
    jobs:
      - lint
      - typecheck
      - deploy:
          context:
            - slack
          requires:
            - lint
            - typecheck
          filters:
            branches:
              only:
                - main
