version: 2.1

orbs:
  node: circleci/node@4.7
  slack: circleci/slack@4.4.2

jobs:
  deploy:
    executor: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: yarn deploy
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1


workflows:
  version: 2
  main:
    jobs:
      - deploy:
          context:
            - slack
