name: Deploy to vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: 18
      - name: Install dependencies
        run: pnpm install
      - name: run deploy to vercel
        run: pnpm deploy-vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
